<h1>Títulos</h1>

<p>
    <a href="<?=$this->url('title-admin/default', array('action' => 'new'))?>">Novo</a>
</p>

<table class="table">

    <tr>
        <th>Id</th>
        <th>Nome</th>
        <th>Calculation</th>
        <th>Acao</th>
    </tr>

    <?php foreach ($this->paginator as $entity): ?>
        <tr>
            <td><?=$entity->getId()?></td>
            <td><?=$entity->getName()?></td>
            <td><?=$entity->getCalculation()?></td>
            <td>
                <a href="<?=$this->url('title-admin/default', array('controller' => 'titles', 'action' => 'edit', 'id' => $entity->getId()))?>">Editar</a>
                <a href="<?=$this->url('title-admin/default', array('controller' => 'titles', 'action' => 'delete', 'id' => $entity->getId()))?>">Deletar</a>
            </td>
        </tr>
    <?php endforeach; ?>

</table>

<?=$this->paginationControl(
    $this->data,
    'Sliding',
    'partials/paginator',
    array(
        'route' => 'title-admin/paginator',
        'options' => array(
            'controller' => 'titles',
            'action' => 'index',
        ),
    )
)?>