<?=$this->headTitle($title = 'Titulo')?>
<h1><?=$this->escapeHtml($title)?></h1>

<?php foreach($this->messages as $message): ?>
    <p>
        <?=$message?>
    </p>
<?php endforeach; ?>
<?php if(!$this->messages): ?>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('user-register', array('controller' => 'index', 'action' => 'register')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
?>
<?php endif; ?>
